### ISSUE TITLE
 only 8 objects

### ISSUE THREAD

**Issue by amgstone** [shammysha/homeassistant-emcd-pool#16]
Only 8 objects. No workers
![zzz](https://user-images.githubusercontent.com/63303107/186719353-ed7018e7-25ab-4513-9b63-b35e741acbe8.jpg)

**Comment by shammysha** [comment]
Please, try new release v2.0.32

**Comment by amgstone** [comment]
I have the newest version. which came out a couple of days ago

**Comment by shammysha** [comment]
![image](https://user-images.githubusercontent.com/65885873/186754152-2b59ea7c-ae4f-47cd-b722-bc13826141ce.png)
Try new version, please

**Comment by amgstone** [comment]
new version install
![zzzz](https://user-images.githubusercontent.com/63303107/186757779-2c5a3cda-0147-4bd1-8871-4c2eb2e4ca2f.jpg)

**Comment by amgstone** [comment]
if I did it through integration, then I don't need to enter anything in configuration.yaml?

**Comment by shammysha** [comment]
Yes. Remove record from configuration.yaml

**Comment by amgstone** [comment]
I did so, but nothing was added except sensor.emcd_amgstone_btc_status

**Comment by shammysha** [comment]
I tested release with API examples from https://emcd.io/pool/api and got worked sensors for workers and status for each pool's coin

I need debug log of component. Please, add lines in configuration.yaml): 
```
logger:
  default: info
  logs:
    custom_components.emcd_pool: debug
```
After that reinstall integration (uninstall, restart HA, install)

**Comment by amgstone** [comment]
done, what to do next?

**Comment by amgstone** [comment]
Error while setting up emcd_pool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/emcd_pool/sensor.py", line 101, in async_setup_entry
    sensor = EMCDRewardsSensor(
TypeError: EMCDRewardsSensor.__init__() got an unexpected keyword argument 'type'

**Comment by shammysha** [comment]
Thank you for log.
Try new release v2.0.33, please.

**Comment by amgstone** [comment]
everything works)). it would be good to add dogecoin logo.
